# Generated by Django 2.1.4 on 2019-01-04 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forum_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_nom', models.CharField(max_length=255)),
                ('forum_description', models.TextField()),
                ('last_post', models.IntegerField(default=None)),
                ('logo_forum', models.ImageField(upload_to='photos/')),
                ('forum_actived', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_texte', models.TextField()),
                ('post_createur', models.CharField(max_length=255)),
                ('post_date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_forum')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_titre', models.CharField(max_length=255)),
                ('topic_createur', models.CharField(max_length=255)),
                ('topic_last_post', models.IntegerField(default=None)),
                ('topic_vu', models.IntegerField(default=None)),
                ('topic_date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('forum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_forum')),
            ],
        ),
        migrations.AddField(
            model_name='forum_post',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_topics'),
        ),
    ]
