# Generated by Django 2.1.4 on 2019-01-08 15:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='post_texte',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
