# Generated by Django 2.1.4 on 2019-01-09 09:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20190108_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='post_texte',
            field=tinymce.models.HTMLField(),
        ),
    ]
