# Generated by Django 2.1.4 on 2019-02-12 10:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20190109_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_topics',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
