# Generated by Django 2.1.4 on 2019-02-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_forum_topics_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='p_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_categorie'),
            preserve_default=False,
        ),
    ]
