# Generated by Django 2.1.4 on 2019-02-14 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0008_auto_20190213_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('description_user', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateTimeField()),
                ('sexe', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=55)),
                ('site_web', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('biographie', tinymce.models.HTMLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
