# Generated by Django 2.1.4 on 2019-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_auto_20190214_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
