# Generated by Django 2.1.4 on 2019-02-14 00:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_auto_20190214_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='biographie',
            field=tinymce.models.HTMLField(default=None),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='date_naissance',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='description_user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='facebook',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='linkedin',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='nom',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='prenom',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='sexe',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='site_web',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='tel',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
