# Generated by Django 2.1.4 on 2019-02-14 00:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_auto_20190214_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='biographie',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='date_naissance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='description_user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='linkedin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='sexe',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='site_web',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='tel',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
