# Generated by Django 2.1.4 on 2019-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_auto_20190214_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_categorie',
            name='order_place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
