# Generated by Django 2.1.4 on 2019-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0014_forum_categorie_order_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='facebook',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='linkedin',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='site_web',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
