# Generated by Django 2.1.4 on 2019-02-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_auto_20190217_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profil',
            name='sexe',
        ),
    ]
