# Generated by Django 2.1.4 on 2019-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_remove_user_profil_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
