# Generated by Django 2.1.4 on 2019-02-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0017_user_profil_edit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics_suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_topics')),
                ('user_suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
