# Generated by Django 2.1.4 on 2019-02-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0018_topics_suivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_message', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_message', tinymce.models.HTMLField()),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_readed', models.BooleanField(default=False)),
                ('destinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.User_profil')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.MessageUser')),
            ],
            options={
                'ordering': ['answer_date'],
            },
        ),
        migrations.RemoveField(
            model_name='forum_topics',
            name='topic_vu',
        ),
        migrations.AlterField(
            model_name='forum_forum',
            name='last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_forum_post', to='tutorial.Forum_post'),
        ),
        migrations.AlterField(
            model_name='forum_topics',
            name='topic_last_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_post', to='tutorial.Forum_post'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Forum_topics'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageuser',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_answer', to='tutorial.Reponse'),
        ),
    ]
