# Generated by Django 2.1.4 on 2019-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0021_forum_forum_last_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='messageuser',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
