# Generated by Django 2.1.4 on 2019-02-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0022_auto_20190226_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageuser',
            name='is_readed',
        ),
        migrations.AddField(
            model_name='reponse',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
